/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.calazans.shoppingcart.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ShoppingCartApplication {
    public static void main(String[] args) {
        SpringApplication.run(ShoppingCartApplication.class);
    }
}
